### PR TITLE
Gyro camera

### PR DESCRIPTION
**Pull request by jakebriggs**
- Added support for gyro aiming
- Changed the Makefile to add in the link to the SceMotion libs
- Changed the Makefile so the "\" are now "/", I don't know if its right but it wouldn't build for me without that
- Added configuration to the menu and CVARS

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Changing \ with / breaks compilation on Windows. Probably to get rid of this we should move to vita-pack-vpk to generate the final vpk.

**Comment by JacobBriggsAckama** [comment]
I'll change it back then, and perhaps add a comment explaining it.

EDIT: Wrong account

**Comment by jakebriggs** [comment]
I'll change it back then, and perhaps add a comment explaining it. Also, I noticed some comments I left in in_psp2.c that are messy, so I'll clean those up

**Comment by jakebriggs** [comment]
AND done

**Pull request merged**
