### PR TITLE
Fixing issue with viewsize and the screen being messed up

### PR DESCRIPTION
**Pull request by Ch0wW**
Also fixes a graphical error when the viewsize is below 100.

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Issue #5?

**Comment by Ch0wW** [comment]
Issue #62 , my bad.

**Comment by Rinnegatamante** [comment]
Screenshot with the PR?

**Comment by Ch0wW** [comment]
viewsize 100 : 
quake00 copy

viewsize 110 : 
quake01 copy

viewsize 120 : 
quake02 copy

viewsize < 100 :
quake03 copy

**Pull request merged**
