### PR TITLE
Merging lots of fixes.

### PR DESCRIPTION
**Pull request by Ch0wW**
Can't automatically merge? Heresy...

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
Conflicts and 2 only commits? <.<

**Comment by Ch0wW** [comment]
Huge squash, and I don't know what would cause the conflicts. But that may be a small textual error.

**Comment by Rinnegatamante** [comment]
You must hate me so much T.T . Can you fix it?

**Comment by Ch0wW** [comment]
Sure, I'll check what may be wrong!

**Pull request closed without merging**
